title = 'Thomas Wilson'
baseURL = "https://www.thomaswilson.xyz"
theme = 'archie-master'

languageCode = "en-uk"
copyright = "© Thomas Wilson"

paginate=5 # articles per page

[params]
  description = 'Thomas Wilson is a software engineer who works with socially responsible companies, living in Oxford.'
	mode="auto" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	Subtitle = ""
  BioStrapLine="I build good software and engineering teams with good<span class='bio__star'>*<span> companies"
  BioStrapLineCaveat="Companies actively working to solve environmental and social issues, not companies building invasive or immoral tools to perpetuate objectively unjust decisions."
  BioListItems = [
    "I am currently leading the engineering team at [Oxwash](https://www.oxwash.com) to help build the future of Laundry.",
    "I write on my [blog](/blog).",
    "I live in Oxford, England.",
    "I'm good at cooking, passionate about cycling, and learning to make my own clothes."
  ]
  mainSections=['blog', 'book-reviews']
  

# Social Tags

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/tjwilson92/"


# Main menu Items

[[menu.main]]
name = "Blog"
url = "/blog"
weight = 2

[[menu.main]]
name = "Book reviews"
url = "/book-reviews"
weight = 2

